Removes all history log code
amgrubb/BloomingLeaf pull request #291
Opened 2021-03-08 04:59 UTC by mvarnum

2021-03-13 23:46 UTC, krhablutzel commented on leaf-ui/index.html
> +        <!-- <div id="analysis-sidebar" class="left-panel"><h3 style="text-align:left; color:#181b1fe3; margin-bottom:5px; margin-left: 10px;">Analysis
I think the analysis sidebar needs to be uncommented now

2021-03-13 23:58 UTC, krhablutzel requested changes
Thanks for making all these changes! I think the analysis sidebar needs to be uncommented so it works again, but otherwise looks great. A lot of changes have been made to model-management since this branch was created, so be prepared for possible merge conflicts. Not quite approving this yet since I'd love to test that the analysis sidebar still works, but overall looks very good!

2021-03-13 23:58 UTC, krhablutzel commented on leaf-ui/js/object/InputAnalysis.js
> +		//this.elementList = getElementsForAnalysis();
Is the InputAnalysis class even used anymore? I know it mirrors an InputAnalysis class in the backend, but I couldn't find it being used anywhere in the frontend. Wondering if we even need to have it

2021-03-13 23:58 UTC, krhablutzel commented on leaf-ui/js/object/InputAnalysis.js
> +// function getElementsForAnalysis() {
Not sure whether we need to leave this... probably related to whether we still need the InputAnalysis class?

2021-03-17 01:20 UTC, krhablutzel approved these changes
This looks great Megan! Thanks for making all these changes; you can probably merge now!

2021-03-17 01:54 UTC, esterzhao approved these changes
Looks good!

2021-03-18 23:51 UTC, merged