Placed intermediate button on the toolbar
amgrubb/BloomingLeaf pull request #449
Opened 2021-06-24 14:26 UTC by Domily11

2021-06-24 15:33 UTC, leshghi requested changes
This looks great to me! Awesome job - thank you. I think you may need to pull from backbone-refactor to get some files/changes out of your pull request. Let me know if you need help getting those out. Also - would you be able to put a thin line between the Assignments List button and the Intermediate Values button? No worries if not but I think it could help separate the two visually.

2021-06-24 15:33 UTC, leshghi commented on leaf-ui/css/style.css
>  }
Remove this file from commit

2021-06-24 15:33 UTC, leshghi commented on leaf-ui/js/initializeElements.js
> -
Remove this file from commit

2021-06-24 15:33 UTC, leshghi commented on leaf-ui/css/analysis_style.css
Remove this file from commit

2021-06-24 15:33 UTC, leshghi commented on leaf-ui/rappid-extensions/AnalysisInspector.js
> +		//'<button id="btn-view-intermediate" class="analysis-btns inspector-btn sub-label green-btn">Intermediate Values</button>',
Can delete this

2021-06-24 15:33 UTC, leshghi commented on leaf-ui/rappid-extensions/AnalysisInspector.js
> +		//'click #btn-view-intermediate': 'openIntermediateValuesTable',
Can delete this line

2021-06-24 15:33 UTC, leshghi commented on leaf-ui/rappid-extensions/AnalysisInspector.js
> +	/**
Can delete this function

2021-06-24 15:33 UTC, leshghi commented on leaf-ui/rappid-extensions/AssignmentsTable.js
> +            $('#rel-intention-assigments').append(relIntentionRow.el);
Remove this file from commit

2021-06-24 15:33 UTC, leshghi commented on leaf-ui/rappid-extensions/BackboneModelsOther.js
> +        linkType:  'and',
Remove this file from commit

2021-06-24 15:33 UTC, leshghi commented on leaf-ui/rappid-extensions/LinkInspector.js
> +    model: joint.dia.CellLink,
Remove this file from commit

2021-06-24 15:33 UTC, leshghi commented on leaf-ui/rappid-extensions/joint.extensions.js
> +joint.dia.CellLink = joint.dia.Link.extend({
Remove this file from commit

2021-06-24 16:18 UTC, Domily11 commented on leaf-ui/css/style.css
>  }
Pls help!!

2021-06-25 15:38 UTC, leshghi approved these changes
Looks great to me. Outstanding issue where you cannot close the IVT but that is fixed in the ae-ivt-backbone branch where we are working on the IVT file so not related to your PR at all. You're all set - thanks

2021-06-28 20:18 UTC, merged