Fixed issue #744
amgrubb/BloomingLeaf pull request #487
Opened 2021-07-08 19:01 UTC by Manarnz

Previously, the config sidebar would not scroll down. Instead, it would keep going downwards everytime a new request is made. It is not exactly issue #744, as the issue changed once the "Started Configurations Revamp in new branch" PR was mereged.

2021-07-09 14:14 UTC, leshghi requested changes
I'm not sure what Issue you're working on - is this supposed to be issue #477 that you were assigned? The problem is actually that the logo hides the configurations even after you scroll down. Scrolling has already been enabled for the sidebar. It would be great to bring the div that holds the config sidebar up above the logo somehow so there is no overlap.

2021-07-09 14:22 UTC, Manarnz commented
> I'm not sure what Issue you're working on - is this supposed to be issue #477 that you were assigned? The problem is actually that the logo hides the configurations even after you scroll down. Scrolling has already been enabled for the sidebar. It would be great to bring the div that holds the config sidebar up above the logo somehow so there is no overlap.

After Angela and I merged our PR, the configInspector would not scroll down. Instead it just kept incrementing downwards as demonstrated in the photo. 
![image](https://user-images.githubusercontent.com/83615524/125092562-77d80600-e09f-11eb-8e00-5838f999d1f7.png)
I fixed this issue in this PR. This is why I stated that it is not exactly issue #477. I will now work on the logo problem, thank you for the clarification!

2021-07-09 14:31 UTC, leshghi commented
> > I'm not sure what Issue you're working on - is this supposed to be issue #477 that you were assigned? The problem is actually that the logo hides the configurations even after you scroll down. Scrolling has already been enabled for the sidebar. It would be great to bring the div that holds the config sidebar up above the logo somehow so there is no overlap.
> 
> After Angela and I merged our PR, the configInspector would not scroll down. Instead it just kept incrementing downwards as demonstrated in the photo.
> ![image](https://user-images.githubusercontent.com/83615524/125092562-77d80600-e09f-11eb-8e00-5838f999d1f7.png)
> I fixed this issue in this PR. This is why I stated that it is not exactly issue #477. I will now work on the logo problem, thank you for the clarification!

Ah got it - In that case can you make an actual issue for that as well and tag it in this PR? If possible it would be awesome if you could work on #477 on this PR as well since the two are related.

2021-07-09 14:32 UTC, leshghi commented
> > > I'm not sure what Issue you're working on - is this supposed to be issue #477 that you were assigned? The problem is actually that the logo hides the configurations even after you scroll down. Scrolling has already been enabled for the sidebar. It would be great to bring the div that holds the config sidebar up above the logo somehow so there is no overlap.
> > 
> > 
> > After Angela and I merged our PR, the configInspector would not scroll down. Instead it just kept incrementing downwards as demonstrated in the photo.
> > ![image](https://user-images.githubusercontent.com/83615524/125092562-77d80600-e09f-11eb-8e00-5838f999d1f7.png)
> > I fixed this issue in this PR. This is why I stated that it is not exactly issue #477. I will now work on the logo problem, thank you for the clarification!
> 
> Ah got it - In that case can you make an actual issue for that as well and tag it in this PR? If possible it would be awesome if you could work on #477 on this PR as well since the two are related.

Also - there is no issue 744, so could you please remove the references to that in this PR? Thanks!

2021-07-09 19:26 UTC, leshghi requested changes
Have you tested this? The configs still overlap with the logo. This might involve a larger css fix/re-arrangement

2021-07-19 18:54 UTC, YesugenB commented
When you go to Analysis view, the Attribution section disappears, and is not there when you go back to Modeling view.

2021-07-19 19:14 UTC, Manarnz commented
> When you go to Analysis view, the Attribution section disappears, and is not there when you go back to Modeling view.

It is supposed to disappear in analysis mode. As for the second part, for some reason it is working for me. Could you please check now?

2021-07-19 19:21 UTC, YesugenB commented
Yup it's fixed now! Thanks

2021-07-19 19:27 UTC, YesugenB commented on leaf-ui/css/style.css
> +   /* box-shadow: inset 0 0 0 1px rgba(0,0,0,0.1),0px 0 0 1px rgba(255,255,255,0.1); */
Can this be removed now?

2021-07-19 19:30 UTC, YesugenB commented on leaf-ui/index.html
> +        <button id="modeling-btn" class="red-btn btn analysis-only" style='display: none';>Modeling</button>
Can we add `""` around `style` instead of `''` so it's consistent

2021-07-19 20:06 UTC, YesugenB commented on leaf-ui/index.html
> +        <button id="modeling-btn" class="red-btn btn analysis-only" style='display: none';>Modeling</button>
And `none';` should be `none;'`?

2021-07-19 20:07 UTC, YesugenB commented on leaf-ui/index.html
>          <!--This is the modal box of Intemdiate Values-->
`Intermediate`

2021-07-19 20:09 UTC, YesugenB commented on leaf-ui/index.html
> +        <button id="simulate-single-path-btn" ; class="btn analysis-only" ;
I'm not sure that we need the` ;` between id and class in this and line 111.

2021-07-19 20:10 UTC, YesugenB commented on leaf-ui/index.html
> +       <!-- <div id="dropdown-model" class="dropdown analysis-only" style='display: none'>
Change quotation marks around `style`

2021-07-19 20:14 UTC, YesugenB approved these changes
Looks good

2021-07-21 02:17 UTC, amgrubb approved these changes
Nice work, it looks great! Please address @YesugenB's comments.

2021-07-21 02:18 UTC, amgrubb requested changes
Sorry, clicked the wrong button. Please address @YesugenB's comment.

2021-07-21 15:01 UTC, Manarnz commented on leaf-ui/index.html
> +       <!-- <div id="dropdown-model" class="dropdown analysis-only" style='display: none'>
This is commented out.

2021-07-21 15:07 UTC, amgrubb approved these changes
Excellent, thanks for making these changes.

2021-07-21 15:17 UTC, merged