Fixed EVO Coloring Bug for State
amgrubb/BloomingLeaf pull request #526
Opened 2021-08-02 20:52 UTC by Domily11

2021-08-03 18:43 UTC, Manarnz approved these changes
It looks good! Great job Cat!!

2021-08-03 18:43 UTC, Manarnz commented on leaf-ui/js/displayAnalysis.js
> +    EVO.setCurTimePoint(isSwitch ? 0 : sliderMax, currentAnalysis);
remove extra space after `;`

2021-08-03 18:43 UTC, Manarnz commented on leaf-ui/js/object/evoObjects.js
> +        //EVO.refresh(analysisResult);
delete it

2021-08-04 15:53 UTC, amgrubb commented
- [ ] This issue includes the problem that `revertNodeValuesToInitial` was never reimplemented.

```
// TODO: Re-write with new models
function revertNodeValuesToInitial() {
```
line ~742 in onFunctions.js

See also same comment in #525

2021-08-04 15:53 UTC, amgrubb requested changes
See comment above for requested additional feature.

2021-08-05 21:46 UTC, Manarnz approved these changes
Looks good!

2021-08-05 21:46 UTC, Manarnz commented on leaf-ui/js/object/evoObjects.js
> +            EVO.revertIntentionsText(graph.getElements(), paper);
Why is `EVO.revertIntentionsText(graph.getElements(), paper);` repeated four times?

2021-08-05 21:46 UTC, Manarnz commented on leaf-ui/js/object/evoObjects.js
> +     *
remove extra line

2021-08-05 21:46 UTC, Manarnz commented on leaf-ui/js/object/evoObjects.js
> +        if(this.isColorBlindMode) {
Add space between `if` and `(this.isColorBlindMode)`
Also, try to change it to `EVO.isColorBlindMode` for consistency

2021-08-05 21:46 UTC, Manarnz commented on leaf-ui/js/object/evoObjects.js
> +        this.isColorBlindMode = isTurningOnColorBlindMode;
Try to change it to `EVO.isColorBlindMode` for consistency

2021-08-05 21:46 UTC, Manarnz commented on leaf-ui/js/onFunctions.js
> +        //curr.attr({text: {fill: 'black'}});
delete line

2021-08-05 21:46 UTC, Manarnz commented on leaf-ui/rappid-extensions/ConfigInspector.js
> +        EVO.refresh(undefined)
Add `;`

2021-08-06 16:00 UTC, amgrubb approved these changes
Approved to merge into ma-issue221

2021-08-06 16:09 UTC, merged