Fixing absTime bugs
amgrubb/BloomingLeaf pull request #531
Opened 2021-08-04 16:29 UTC by i-m-foster

Closes #527 and #530

2021-08-04 16:32 UTC, Domily11 commented on leaf-ui/rappid-extensions/ElementInspector.js
Maybe delete this line? Up to you tho

2021-08-04 16:42 UTC, Domily11 requested changes
Small additional bug, the error doesn't pop back up if you added the absolute time then immediately took it off

2021-08-04 16:42 UTC, Domily11 commented on leaf-ui/rappid-extensions/ElementInspector.js
> +                console.log('hi');
Remove console

2021-08-04 20:33 UTC, YesugenB approved these changes

2021-08-04 21:11 UTC, Domily11 requested changes
One bug:
- if you chose a begin without putting an absolute time and the error message appears, the message doesn't disappear even tho the begin is emptied

2021-08-04 21:11 UTC, Domily11 commented on leaf-ui/rappid-extensions/ElementInspector.js
> +        }
Delete extra space

2021-08-05 14:23 UTC, Domily11 approved these changes

2021-08-09 17:21 UTC, amgrubb commented
It still not working quite correctly. Maybe we can push this as a partial fix and revisit in the future.

2021-08-09 17:23 UTC, amgrubb approved these changes
It's still not working quite correctly. Maybe we can push this as a partial fix and revisit in the future.
If so, add a new issue to improve the interaction of the error message.

2021-08-09 18:06 UTC, merged