Reimplemented the new backbone structure in #btn-clear-elabel
amgrubb/BloomingLeaf pull request #534
Opened 2021-08-09 18:14 UTC by Manarnz

2021-08-10 16:09 UTC, Domily11 requested changes
Two things to address:
 - A small bug where after you clear labels and click on the node, the function type label disappears as well
 - Not sure how clear labels is supposed to act with NB links

2021-08-10 16:09 UTC, Domily11 commented on leaf-ui/js/onFunctions.js
>              var cellView = element.findView(paper);
Maybe combine this line with the next line? It's only called once

2021-08-12 18:04 UTC, Domily11 approved these changes

2021-08-12 19:03 UTC, amgrubb approved these changes
Looks great, good job!

2021-08-12 19:05 UTC, merged