Fixed chart issue
amgrubb/BloomingLeaf pull request #536
Opened 2021-08-10 14:34 UTC by Manarnz

Before, when changing abs time, the graph would update even though it does not need to.

2021-08-10 15:12 UTC, YesugenB approved these changes, later dismissed

2021-08-10 19:01 UTC, i-m-foster requested changes
The chart no longer updates for non-UD functions. Also, previously in UD functions whenever you updated the function type or satisfaction value the chart changed, but now it only changes when you click add.

2021-08-12 18:10 UTC, i-m-foster approved these changes

2021-08-12 19:05 UTC, amgrubb approved these changes
I like this solution. 👍

2021-08-12 19:06 UTC, merged