Fixed issues below
amgrubb/BloomingLeaf pull request #543
Opened 2021-08-12 18:06 UTC by Manarnz

Reimplement clear results and configs in analysis mode
The slider does not change sat val when EVO is off and result is selected

2021-08-12 18:39 UTC, YesugenB commented
The fonts for function type and initial satisfaction value become smaller when you press clear in analysis view?

2021-08-12 19:18 UTC, YesugenB submitted a review, later dismissed
Looks great!

2021-08-12 19:31 UTC, YesugenB approved these changes, later dismissed

2021-08-13 17:29 UTC, Domily11 requested changes
I thought the font looked a bit odd when it is in EVO mode, did you put an outline around the text?

2021-08-13 20:43 UTC, angelac2023 commented on leaf-ui/js/object/evoObjects.js
> +        else {// If EVO is off
Can you put this comment above?

2021-08-13 20:43 UTC, angelac2023 commented on leaf-ui/js/object/evoObjects.js
> +            if (analysisResult !== undefined && analysisResult.get('selected')) {// If a result is selected
See previous line.

2021-08-13 20:44 UTC, angelac2023 reviewed
Other than the comment uniformity, looks good!

2021-08-13 20:58 UTC, angelac2023 approved these changes

2021-08-13 21:10 UTC, amgrubb approved these changes
Nice work!

2021-08-13 21:27 UTC, merged