Implemented the remove so that it takes into account of NB links
amgrubb/BloomingLeaf pull request #544
Opened 2021-08-12 20:32 UTC by Domily11

2021-08-12 20:46 UTC, Manarnz requested changes
Whenever a change is made in the paper the initial sat value disappears. Overall, great job!

2021-08-12 20:46 UTC, Manarnz commented on leaf-ui/js/onFunctions.js
> +             //   if (localLinks[i].getSourceElement().prop("id") == node["id"] || localLinks[i].getTargetElement().prop("id") == node["id"]) {
delete line as well as line 697

2021-08-12 20:46 UTC, Manarnz commented on leaf-ui/rappid-extensions/LinkInspector.js
> +            target.get('intention').getUserEvaluationBBM(0).set('assignedEvidencePair', '(no value)')
Add `;`

2021-08-13 21:03 UTC, Manarnz approved these changes, later dismissed
Great job Cat!!

2021-08-13 21:03 UTC, Manarnz commented on leaf-ui/js/onFunctions.js
> +        //Verify if it is possible to remove the NB tag from source and target
Add space between `//` and `Verify`

2021-08-13 21:15 UTC, amgrubb submitted a review, later dismissed
Great job!

2021-08-13 21:17 UTC, amgrubb approved these changes

2021-08-13 21:18 UTC, merged