Fixed absTime and element inspector bugs
amgrubb/BloomingLeaf pull request #556
Opened 2021-08-19 15:07 UTC by YesugenB

Closes #537 and #535

2021-08-19 18:38 UTC, Domily11 approved these changes, later dismissed
Once you fix the bugs I mentioned you are good to go!!

2021-08-19 20:23 UTC, i-m-foster submitted a review, later dismissed

2021-08-19 23:55 UTC, amgrubb requested changes
A couple of small changes to clean up the code. Otherwise looks good.

2021-08-19 23:55 UTC, amgrubb commented on leaf-ui/rappid-extensions/BackboneModelsIntention.js
> +            // // If the function is C or UD & C set refEvidencePair to initValue
Can this commented out code be removed?

2021-08-19 23:55 UTC, amgrubb commented on leaf-ui/rappid-extensions/BackboneModelsIntention.js
> +            console.log(this)
Remove console log?

2021-08-19 23:55 UTC, amgrubb commented on leaf-ui/rappid-extensions/ElementInspector.js
> +       // console.log(this.intention)
remove this line

2021-08-20 13:44 UTC, i-m-foster approved these changes

2021-08-20 13:45 UTC, amgrubb approved these changes

2021-08-20 13:45 UTC, merged