Config names no longer overlap
amgrubb/BloomingLeaf pull request #572
Opened 2021-09-14 21:09 UTC by Vbeany

Known bugs: Changing name of last config gives Results NaN for next config. Made separate issue.

2021-09-14 21:23 UTC, amgrubb commented
I changed the base to `sep21-bugs`.

2021-09-17 19:35 UTC, i-m-foster approved these changes
It looks good to me! I would add the bug number it fixes in a comment so it's easy to see and maybe also add the bug number to the linked issues section on the side.

2021-09-18 17:36 UTC, anishaj149 requested changes
(Worked with Kathleen so her comment contains necessary changes.) :)

2021-09-18 17:38 UTC, krhablutzel requested changes
This works well when the user has not renamed Requests (other than the Result/Request typo). However, it generates some odd behavior when the user has renamed the Request (see comments below).

2021-09-18 17:38 UTC, krhablutzel commented on leaf-ui/rappid-extensions/ConfigInspector.js
> +                configModel = new ConfigBBM({ name: "Result " + 1, results: new ResultCollection([]) });
We want to call these "Request", not "Result"

2021-09-18 17:38 UTC, krhablutzel commented on leaf-ui/rappid-extensions/ConfigInspector.js
> +            var nameIndex = parseInt(this.collection.at(this.collection.length - 1 ).get('name').split(' ').pop()) + 1;
When a request is renamed to something not containing a number, this replaces the last word in the name with `NaN`. This also returns odd results when a Request is named just a number or has an empty name. (Also, less importantly, if we rename a Request to a different number, we start counting from that number even if that isn't the total number of Requests ever generated - not sure whether we like this behavior.)

<img width="204" alt="Screen Shot 2021-09-18 at 13 34 47" src="https://user-images.githubusercontent.com/59173829/133897526-d4eef968-95d4-4a5e-b31c-c0e9aea3101d.png">

2021-09-18 18:54 UTC, krhablutzel approved these changes
Approving this since the noted changes are covered in separate issue #573

2021-09-18 19:24 UTC, merged