Cleaned up evoObjects and viewObjects
amgrubb/BloomingLeaf pull request #582
Opened 2021-09-17 21:28 UTC by Vbeany

Closes #373

2021-09-18 18:52 UTC, krhablutzel approved these changes
These changes all look great! I had one question about some parameters that got removed, but everything seems to still work well. Thanks for cleaning up these files!

2021-09-18 18:52 UTC, krhablutzel commented on leaf-ui/js/object/viewObjects.js
> -						callback: function (value, index, values) {
Did we double-check that these aren't being passed in from elsewhere?

2021-09-18 20:27 UTC, Domily11 requested changes
Idk why the intentionColoring class is back but can you remove that and integrate colorblind function into EVO?

2021-09-18 20:27 UTC, Domily11 commented on leaf-ui/js/object/evoObjects.js
> +        this.evals = {};
Remove blank

2021-09-25 20:09 UTC, Domily11 commented on leaf-ui/js/object/evoObjects.js
>  class IntentionColorVis {
Do we know if this is necessary and if we can merge into evo as well?

2021-09-28 21:46 UTC, merged