Fixed #546
amgrubb/BloomingLeaf pull request #594
Opened 2021-10-05 21:02 UTC by Domily11

2021-10-21 22:21 UTC, YesugenB reviewed
Should `getElementById` be changed to `getElementByNum`? 
<img width="1813" alt="Screen Shot 2021-10-21 at 6 18 44 PM" src="https://user-images.githubusercontent.com/59470488/138364794-9dfc1c37-0cca-46fd-aac8-e47771328d2c.png">

2021-10-21 22:25 UTC, YesugenB requested changes
Looks good! Just left a comment about error detection

2021-10-21 23:20 UTC, krhablutzel reviewed
Looks good to me! Suggested a few small changes, and definitely change `getElementById` to `getElementByNum` in `errordetection.js`, but then you'll be ready to merge.

2021-10-21 23:20 UTC, krhablutzel commented on leaf-ui/js/backendComm.js
> +	var ids = getNums(backendErrorMsg);
perhaps this variable could be `nums` rather than `ids`, now that we're calling them nums everywhere else?

2021-10-21 23:20 UTC, krhablutzel commented on leaf-ui/js/backendComm.js
>  	// this regex matches for an N, followed by 4 digits
if this matches three digits now, perhaps update the comment?

2021-10-22 20:51 UTC, YesugenB approved these changes
😎

2021-10-22 20:52 UTC, merged