actors now log merged intentions
amgrubb/BloomingLeaf pull request #661
Opened 2022-06-14 18:47 UTC by anishaj149

Originally, intentions will log their new actor objects, but actors would not keep track of new intentions. I added a method to update the elements embedded in an actor and added a line in the merge algorithm so that a new actor object will collect the unique IDs of any intentions that the actor version in the other model has but the new one doesn't. (When MMain.DEBUG = true console outputs will show when an intention has been added to a new actor) (Changes in MMain are not important, just for running stuff)

2022-06-15 14:02 UTC, Vbeany approved these changes
Looks good, muy excelente

2022-06-15 15:02 UTC, amgrubb commented on leaf-analysis/src/merge/MMain.java
> +	public final static boolean DEBUG = true;
please set debug back to false.

2022-06-15 15:27 UTC, amgrubb requested changes
Please review and update MMain.java.

2022-06-15 15:27 UTC, amgrubb commented on leaf-analysis/src/merge/MMain.java
> +		String inputFile1 = "S1-Part4.json";
I don't think these should be checked in/hard coded.

2022-06-15 15:27 UTC, amgrubb commented on leaf-analysis/src/merge/MMain.java
> +//			if (args.length == 4) {
Why are these commented out?

2022-06-22 15:26 UTC, amgrubb approved these changes

2022-06-22 20:25 UTC, merged