Summer23 bug fixes
amgrubb/BloomingLeaf pull request #725
Opened 2023-07-07 14:18 UTC by kkung9

2023-07-07 18:04 UTC, emruckle approved these changes, later dismissed
Code is clear and well commented. Addresses issues with clearing evolving function labels, changing color palettes, and selecting a state in next state when there are a high number of possible states. Does not break simulation, setting evolving functions, or choosing next states

2023-10-02 21:33 UTC, mollyd13 requested changes
Code looks good and has sufficient comments! Testing confirms that bugs #708, #669, #667, #687, #686, and #663 are fixed successfully. However, issue #666 seems to not be fixed. When you apply a filter that leads to having 0 states, a popup appears telling you it is not allowed and the filter is unselected, but the number of states remains at 0 you can no longer save and close next state.

2023-10-15 14:41 UTC, mollyd13 approved these changes
Reviewed issue #666 fix, and the issue is resolved. The code is well commented and does not break any other features.

2023-10-18 13:04 UTC, amgrubb commented
Replaced by #726.

2023-10-18 13:04 UTC, closed without merging